<?php

class docPHP_natives_mr {

    public static function mail() {
        ?>
        <p>Cette classe vous permet d'envoyer un mail depuis votre application en une ligne de code (utilise les paramètres SMTP de <em>config.class.php</em>)</p>
        <?php
        js::monaco_highlighter('<?php\n' .
                '$from="your.mail@your-smtp.com";\n' .
                '$from_name="Your Name";\n' .
                '$to="target@mail.com";\n' .
                '$subject="The Subject";\n' .
                '$msg="Hello World";\n' .
                '(new mail())->send($from, $from_name, $to, $subject, $msg);\n' .
                '?>'
        );
    }

    public static function maskNumber() {
        ?>
        <p>Cette classe permet de formater l'affichage d'un nombre dans un INPUT de type text</p>
        <?php
        js::monaco_highlighter('<?php\n' .
                'maskNumber::set("masknumber");\n' .
                '$form=new form();\n' .
                '$form->input("Nombre", "masknumber");\n' .
                '$form->submit("btn-primary");\n' .
                'echo $form->render();\n' .
                'if(isset($_POST["masknumber"])){\n' .
                '    maskNumber::get("masknumber"); //convertit les saisies dans $_POST\n' .
                '}\n' .
                '?>'
        );
        ?>
        <p>Attention ! maskNumber::set() doit être executé avant l'exécution du formulaire ! <br />
            Résultat :</p>
        <?php
        maskNumber::set("masknumber");
        $form = new form();
        $form->input("Nombre", "masknumber");
        $form->submit("btn-primary");
        echo $form->render();
    }

    public static function math() {
        ?>
        <p>Cette classe contient quelques méthodes statiques mathématiques de base ainsi que des fonctions pour vérifier le type de variables</p>
        <?php
    }

    public static function messageries() {
        ?>
        <p>Cette classe gère la messagerie, elle permet d'envoyer, de réceptionner ou de supprimer un message entre les utilisateurs de l'application.</p>
        <?php
        js::monaco_highlighter('<?php\n' .
                '//Purge les messages de plus de deux ans\n' .
                'messagerie::purge_msg($table_msg, $years = 2);\n' .
                '//Créé une interface de messagerie pour les utilisateurs\n' .
                'new messagerie($table_user, $tuple_user);\n' .
                '?>'
        );
    }

    public static function mocodo() {
        ?>
        <p>Cette classe permet de générer une representation graphique d'une base de donnée.</p>
        <?php
        js::monaco_highlighter('<?php\n' .
                '$db = [\n' .
                '    "rang" => [\n' .
                '    ["id", "int", true],\n' .
                '    ["nom", "string", false],\n' .
                '],\n' .
                '"user" => [\n' .
                '["id", "int", true],\n' .
                '        ["login", "string", false],\n' .
                '        ["psw", "psw", false],\n' .
                '        ["rang", "rang", false],\n' .
                '    ],\n' .
                '];\n' .
                '$mocodo = new mocodo($db);\n' .
                'echo $mocodo->get_text() . "<hr>"; // Affiche le texte généré\n' .
                'echo $mocodo->get_svg() . "<hr>"; // Affiche le SVG\n' .
                'echo $mocodo->get_zip(); // Affiche le lien ZIP\n' .
                '?>'
        );
        ?>
        <h2 class="text-center">Résultat</h2>
        <hr/>
        <!-- Generated by Mocodo 4.3.2 -->
        <svg width="236" height="120" viewBox="0 0 236 120" xmlns="http://www.w3.org/2000/svg">
            <rect x="0" y="0" width="236" height="120" fill="#f5f5f5" stroke="#808080" stroke-width="1" stroke-dasharray="2,2"></rect><!-- Entity USER -->
            <g>
                <g>
                    <rect x="41" y="9" width="44" height="25" fill="#80cdc1" stroke="#808080" stroke-width="1" stroke-dasharray="2,2" opacity="1"></rect>
                    <rect x="41" y="34" width="44" height="77" fill="#c7eae5" stroke="#808080" stroke-width="1" stroke-dasharray="2,2" opacity="1"></rect>
                    <rect x="41" y="9" width="44" height="102" fill="none" stroke="#35978f" stroke-width="2" opacity="1"></rect>
                    <line x1="41" y1="34" x2="85" y2="34" stroke="#35978f" stroke-width="1"></line>
                </g>
                <text x="46" y="26.75" fill="#000000" font-family="Verdana" font-size="12">
                    USER
                </text>
                <text x="46" y="51.8" fill="#000000" font-family="Verdana" font-size="12">
                    id
                </text>
                <line x1="46" y1="54" x2="58" y2="54" stroke="#000000" stroke-width="1"></line>
                <text x="46" y="68.8" fill="#000000" font-family="Verdana" font-size="12">
                    login
                </text>
                <text x="46" y="85.8" fill="#000000" font-family="Verdana" font-size="12">
                    psw
                </text>
                <text x="46" y="102.8" fill="#000000" font-family="Verdana" font-size="12">
                    rang
                </text>
            </g><!-- Entity RANG -->
            <g>
                <g>
                    <rect x="149" y="26" width="46" height="25" fill="#80cdc1" stroke="#808080" stroke-width="1" stroke-dasharray="2,2" opacity="1"></rect>
                    <rect x="149" y="51" width="46" height="43" fill="#c7eae5" stroke="#808080" stroke-width="1" stroke-dasharray="2,2" opacity="1"></rect>
                    <rect x="149" y="26" width="46" height="68" fill="none" stroke="#35978f" stroke-width="2" opacity="1"></rect>
                    <line x1="149" y1="51" x2="195" y2="51" stroke="#35978f" stroke-width="1"></line>
                </g>
                <text x="154" y="43.75" fill="#000000" font-family="Verdana" font-size="12">
                    RANG
                </text>
                <text x="154" y="68.8" fill="#000000" font-family="Verdana" font-size="12">
                    id
                </text>
                <line x1="154" y1="71" x2="166" y2="71" stroke="#000000" stroke-width="1"></line>
                <text x="154" y="85.8" fill="#000000" font-family="Verdana" font-size="12">
                    nom
                </text>
            </g><!-- Link from &quot;id&quot; (USER) to &quot;id&quot; (RANG) -->
            <path d="M85 98.5 C117 81.5 106.33 64.5 149 64.5" fill="none" stroke="#bf812d" stroke-width="2"></path>
            <polygon points="149 64.5 137 70.5 141 64.5 137 58.5" fill="#bf812d" stroke-width="0"></polygon>
            <circle cx="85" cy="98.5" r="2" stroke="#bf812d" stroke-width="2" fill="#bf812d"></circle>
        </svg>
        <hr/>
        <a class="btn btn-primary"><span class="bi bi-file-earmark-zip-fill"><span class="visually-hidden">&nbsp;</span></span> test.zip</a>
        <p>(Note : Ce bouton de démonstration est désactivé)</p>
        <hr/>
        les arrangements, couleurs et polices sont paramétrable via des parametres facultatif du constructeur et des constantes de classe (exemple : mocodo::ARRANGE_ballanced_1)
        <?php
    }

    public static function modal() {
        ?>
        <p>"Modal" est une classe permettant d'afficher des modals (appelées aussi layout ou pop-in). Une "modal" s'ouvre lors d'un clic sur un lien lui correspondant</p>
        <?php
        js::monaco_highlighter('<?php\n' .
                '$a_text="Cliquez ici pour ouvrir la modal";\n' .
                '$id="demo_modal";\n' .
                '$title="(pop-up)";\n' .
                '$titre="Démonstration";\n' .
                '$data="<p class="text-center">Bienvenue sur la démonstration de modals</p>";\n' .
                '$class="";\n' .
                'echo (new modal())->link_open_modal($a_text, $id, $title, $titre, $data, $class);\n' .
                '?>'
        );
        ?>
        <p>Résultat :</p>
        <?php
        echo (new modal())->link_open_modal("Cliquez ici pour ouvrir la modal", "demo_modal", "(pop-up)", "Démonstration", "<p class=\"text-center\">Bienvenue sur la démonstration de modal</p>", "");
    }

    public static function monaco_editor() {
        ?>
        <p>Cette classe génère un monaco_editor afin d'editer le code du projet courant</p>
        <p class="alert alert-danger">/!\ cette classe est à placer précautionneusement dans une partie administration restreinte !</p>
        <?php
        js::monaco_highlighter('<?php\n'
                . 'new monaco_editor();\n'
                . '?>');
    }

    public static function openweather() {
        ?>
        <p>Cette classe permet d'afficher la météo d'une ville en temps réel (utilise openweather et nécessite une clé API)</p>
        <?php
        js::monaco_highlighter('<?php new openweather($api_key, $city); ?>');
        ?>
        <p>Le résultat est le suivant (exemple fictif) :</p>        
        <div class = "openwether">
            <p>
                <span class = "dt">Météo de [$city] (<?php date("d/m H:i"); ?>)</span><br/>
                <span class = "weather"><span><img src = "../commun/openweather/01d.png" alt = ""><span>
                            </span>Ciel clair</span></span><br><span class = "temp">Température : 19°C</span><br/>
                    <span class = "pressure">Pression : 1016 Hpa</span><br/>
                    <span class = "humidity">Humidité : 51%</span><br/>
                    <span class = "wind">Vent : 10km/h, 120.0° (Sud-Est)</span><br/>
            </p>
        </div>
        <?php
    }

    public static function pagination() {
        ?>
        <p>Cette classe gère la pagination dans une page</p>
        <?php
        js::monaco_highlighter('<?php\n'
                . '$get = "p"; //correspond a $_GEY["p"]\n'
                . '$per_page = 100;\n'
                . '$count_all = mon_entite::get_count();\n'
                . '$pagination = pagination::get_limits($get, $per_page, $count_all);\n'
                . 'foreach (mon_entite::get_table_array("1=1 limit :l1,:l2;",[":l1"=>$pagination[0], ":l2"=>$pagination[1]]) as $value) {\n'
                . '    //affichage des informations\n'
                . '}\n'
                . '//affiche le menu de pagination\n'
                . 'pagination::print_pagination($get, $pagination[3]);\n'
                . '?>');
    }

    public static function paypal() {
        ?>
        <p class="alert alert-warning">
            Le SDK PHP de Paypal est obselette, bien que fonctionant toujours, il sera supprimé a therme.
            Previlégiez d'utiliser ou migrer sur Stripe.
        </p>
        <p>Cette classe permet de créer, vérifier et exécuter des paiements via l'API REST de PayPal</p>
        <p>Exemple d'utilisation :</p>
        <?php
        js::monaco_highlighter('<?php\n' .
                '//liste des produits que veut acheter l\'utilisateur\n' .
                '$item_list = [\n' .
                '    [\n' .
                '        "Name" => "produit1",\n' .
                '        "Price" => 10.50,\n' .
                '        "Quantity" => 1\n' .
                '    ],\n' .
                '    [\n' .
                '        "Name" => "produit2",\n' .
                '        "Price" => 1.99,\n' .
                '        "Quantity" => 5\n' .
                '    ]\n' .
                '];\n\n' .
                '//Id et Secret renseignés dans l\'application de l\'API REST de PayPal\n' .
                '$clientId="Votre-clientId";\n' .
                '$clientSecret="Votre-clientSecret";\n' .
                '$paypal = new paypal($clientId, $clientSecret);\n\n' .
                'if (!isset($_GET["paypal_action"])) {\n' .
                '    $_GET["paypal_action"] = "";\n' .
                '}\n' .
                'switch ($_GET["paypal_action"]) {\n' .
                '    case "return":\n' .
                '        $payment = $paypal->get_payment($_GET["paymentId"]);\n' .
                '        //TODO: vérifier les données du paiement\n' .
                '        //Exécute le paiement\n' .
                '        $paypal->execute_payment($payment);\n' .
                '        //TODO : envoyer une copie de la facture par mail\n' .
                '        js::alertify_alert_redir("Paiement accepté! retour à l\'accueil", "index.php");\n' .
                '        break;\n' .
                '    case "cancel":\n' .
                '        js::alertify_alert_redir("Vous avez annulé le paiement, retour à l\'accueil", "index.php");\n' .
                '        break;\n' .
                '    default:\n' .
                '        $url = "http://monsite.fr/" . strtr(application::get_url(["paypal_action"]), ["&amp;" => "&"]);\n' .
                '        //créé le paiement et retourne le lien de paiement pour l\'utilisateur ou false en cas d\'erreur\n' .
                '        if ($link = $paypal->create_payment(\n' .
                '                $item_list, 20, "Ventes de monsite.fr", $url . "paypal_action = return", $url . "paypal_action = cancel"\n' .
                '                )) {\n' .
                '            //affiche le lien pour le paiement ( à fournir à l\'utilisateur)\n' .
                '            //A adapter si vous voulez afficher un bouton PayPal "officiel"\n' .
                '            echo html_structures::a_link($link, "Payer");\n' .
                '        }\n' .
                '        break;\n' .
                '}\n' .
                '?>'
        );
        ?>
        <p>Plus de renseignements dans la documentation technique et sur <a href="https://developer.paypal.com" target="_blank">PayPal Developer</a></p>
        <hr/>
        <?php
        self::stripe();
    }

    public static function php_finediff() {
        ?>
        <p>Permet d'afficher les différences entre deux chaînes de caractères</p>
        <?php
        js::monaco_highlighter('<?php\n'
                . 'echo php_finediff::DiffToHTML("Texte de départ", "Texte final");'
                . '\n?>');
        debug::print_r(php_finediff::DiffToHTML("Texte de départ", "Texte final"));
    }

    public static function php_header() {
        ?>
        <p>Cette classe permet de modifier le header HTTP</p>
        <?php
        js::monaco_highlighter('<?php\n'
                . '// Renseigne le type (mime) du document. Renseignez juste l\'extension du fichier ( par exemple "json" ou "csv"),\n'
                . '// la fonction sera retrouvée le mime corespondant.\n'
                . '(new php_header())->content_type($type, $force_upload_file=false);\n'
                . '// Redirige l\'utilisateur (immédiatement ou avec un délai)\n'
                . '(new php_header())->redir($url, $second=0);\n'
                . '// Définit le statut code de la page, si le statut code est invalide, le code 200 est utilisé par défaut\n'
                . '(new php_header())->status_code($code);\n'
                . '?>');
    }

    public static function php_simple_formatter() {
        ?>
        <p>Cette classe permet de formater (réindenter) du code php/html/js</p>
        <?php
        js::monaco_highlighter('<?php\n'
                . '$formated_code = (new php_simple_formatter())->format($code)\n'
                . '?>');
    }

    public static function phpini() {
        ?>
        <p>
            Cette classe permet de gérer des profils de configuration PHP (comme avoir plusieurs fichiers php.ini interchangeable à volonté)            
        </p>
        <?php
        js::monaco_highlighter('<?php\n'
                . '// Affiche l\'interface pour créer vos propres profils de configuration.\n'
                . '// Est accessible de base par le fichier html/index.php -> PHPini\n'
                . 'phpini::admin();\n\n'
                . '//Charge un profil standard\n'
                . 'phpini::set_mode(phpini::MODE_DEFAULT);\n\n'
                . '//Les différents profils standards sont :\n'
                . '//Configuration par défaut telle que décrite dans la documentation officielle de php.ini\n'
                . 'phpini::MODE_DEFAULT;\n\n'
                . '//Configuration de développement telle que décrite dans la documentation officiele de php.ini\n'
                . 'phpini::MODE_DEV;\n\n'
                . '//Configuration de production telle que décrite dans la documentation officiel de php.ini\n'
                . 'phpini::MODE_PROD;\n\n'
                . '//Configuration de développement conseillé pour DWF\n'
                . 'phpini::MODE_DWF_DEV;\n\n'
                . '//Configuration de production conseillée pour DWF\n'
                . 'phpini::MODE_DWF_PROD;\n\n'
                . '//Charge un profil de configuration de votre création\n'
                . 'phpini::set_mode(phpini::MODE_CUSTOM,"mon_profil");\n\n'
                . '?>');
    }

    public static function pollinanitons() {
        ?>
        <p>Cette classe permet d'utiliser des outils d'IA en passant par les endpoint de pollinations </p>
        <?php
        js::monaco_highlighter('<?php\n'
                . '//Affiche une immage généré par IA\n'
                . 'echo html_structures::img(pollinations::image_src("perfect realistic landscape of forest"));\n'
                . '//Affiche un texte généré par IA\n'
                . 'echo pollinations::text("ecris un commentaire positif sur un stylo 4 couleur");\n'
                . '//Génére un audio généré par IA\n'
                . 'echo tags::tag("audio", ["controls" => "true", "src" => pollinations::audio_src("Raconte moi une histoire pour enfant")]);\n'
                . '?>');
    }

    public static function printer() {
        ?>
        <p>Cette classe permet l'export de données aux formats PDF, CSV ou QRCode,<br />
            le script d'export est <i>html/commun/printer.php</i></p>
        <?php
        js::monaco_highlighter('<?php\n'
                . '//Affiche un bouton d\'export PDF\n'
                . '//(le contenu doit être en HTML sans les balises html et head)\n'
                . 'echo printer::PDF($content, $filename);\n\n'
                . '//Affiche un bouton d\'export CSV\n'
                . '//(le contenu doit être un array a 2 dimentions)\n'
                . 'echo printer::CSV($content, $filename);\n\n'
                . '//Affiche un bouton d\'export QRCODE\n'
                . '//(le contenu doit être un text ou une URL)\n'
                . 'echo printer::QRCODE($content, $get_png_b64 = false);\n\n'
                . '//affiche directement le QRCode\n'
                . '//(l\'image est recupéré en PNG base64)\n'
                . 'echo html_structures::img(printer::QRCODE($content, $get_png_b64 = true));\n'
                . '?>');
    }

    public static function pseudo_cron() {
        ?>
        <p>Cette classe permet de lancer des "pseudo cron", <br />
            contairement à des vrais cron qui s'executent à des heures fixes planifiées par le système, <br />
            ici les pseudos cron s'exécutent : lors d'une activité utilisateur et s'il n'a pas été exécuté depuis un certain temps défini.</p>
        <?php
        js::monaco_highlighter('<?php\n'
                . '// Instanciation du système de pseudo cron en utilisant un registre json (ou SQL par defaut)\n'
                . '//pseudo_cron est un singleton\n'
                . '$pcron = pseudo_cron::get_instance("json");\n\n'
                . '// Exécute la fonction lors d\'une activité utilisateur \n'
                . '// et si la fonction n\'a pas été appelée au cours des dernières 24 heures (86400 secondes) \n'
                . '$nom = "world";\n'
                . '$pcron->fn(86400, function($nom){\n'
                . '    echo "hello ".$nom;\n'
                . '},[$nom]);\n\n'
                . '// Ou même fonction en utilisant le "use" \n'
                . '$nom = "world";\n'
                . '$pcron->fn(86400, function() use ($nom){\n'
                . '    echo "hello ".$nom;\n'
                . '});\n\n'
                . '// si la fonction retourne un résultat il peut être récupéré,\n'
                . '// si la fonction n\'est pas exécuté fn() retourne null\n'
                . '$result = $pcron->fn(86400, function(){return "hello world";});\n'
                . 'if($result !== null){\n'
                . '    echo $result;\n'
                . '}\n\n'
                . '// Exécute un fichier (toujours dans les mêmes conditions)\n'
                . '// le fichier est exécuté dans une console !\n'
                . '$pcron->file(86400,"mon_chemin/mon_script.php");\n'
                . '?>');
        ?>
        <p>L'intéret des cron étant de pouvoir lancer des opérations lourdes à un rythme régulier sans ralentir l'utilisateur <br />
            il est possible de lancer un pseudo cron de façon "asynchrone" en utilisant un service et la methode service::HTTP_POST().
        </p>
        <?php
        js::monaco_highlighter('<?php\n'
                . 'pseudo_cron::get_instance()->fn(86400,function(){\n'
                . '    service::HTTP_POST("http://localhost/mon_projet/services/index.php", ["service"=>"mon_service"]);\n'
                . '});\n'
                . '?>');
        ?>
        <p>Les pseudos cron sont renseignés dans un registe ( soit un fichier json soit une table en base de données ) <br />
            une entrée est supprimée si elle n'est pas mise à jour (exécutée) pendant 1 an, cette durée peut être modifiée via la méthode</p>
        <?php
        js::monaco_highlighter('<?php pseudo_cron::get_instance()->set_clear(31536000); ?>');
    }

    public static function ratioblocks() {
        ?>
        <p>Cette classe permet d'afficher un bloc css avec les proportions passées en paramètres.</p>
        <?php
        js::monaco_highlighter('<?php new ratioblocks($id, $width, $ratio, $contenu); ?>');
    }

    public static function reveal() {
        ?>
        <p>
            Cette classe permet de créer un diaporama avec la librairie reveal <br />
            Il n'est pas recommandé d'avoir plusieurs diaporamas sur la même page.
        </p>
        <?php
        $reveal = new reveal($width = "100%", $height = "300px", $theme = "white");
        js::monaco_highlighter('<?php\n'
                . '$reveal = new reveal($width = "100%", $height = "300px", $theme = "white");\n'
                . '$reveal->start_reveal();\n'
                . '?>\n'
                . '<section><p style="font-size: 48px;">Ceci est un Reveal</p></section>\n'
                . '<section>\n'
                . '    <section><p style="font-size: 48px;">Reveal est une librairie JS qui permet de faire des présentations en HTML</p></section>\n'
                . '    <section><p style="font-size: 48px;">Le PowerPoint est mort, vive le Reveal !</p></section>\n'
                . '</section>\n'
                . '<section><p style="font-size: 48px;">Site officiel de Reveal : <br /><a href="http://lab.hakim.se/reveal-js/">http://lab.hakim.se/reveal-js/</a></p></section>\n'
                . '<?php\n'
                . '$reveal->close_reveal();\n'
                . '?>');
        echo html_structures::hr();
        $reveal->start_reveal();
        ?>
        <section><p style="font-size: 48px;">Ceci est un Reveal</p></section>
        <section>
            <section><p style="font-size: 48px;">Reveal est une librairie JS qui permet de faire des présentations en HTML</p></section>
            <section><p style="font-size: 48px;">Le PowerPoint est mort, vive le Reveal !</p></section>
        </section>
        <section>
            <p style="font-size: 48px;">Site officiel de Reveal : <br />
                <a href="http://lab.hakim.se/reveal-js/">http://lab.hakim.se/reveal-js/</a>
            </p>
        </section>
        <?php
        $reveal->close_reveal();
    }

    public static function reversoLib() {
        ?>
        <p>Cette classe utilise l'API de Reverso pour corriger un texte et 
            vous affiche les corrections à appliquer au texte grâce à la librairie finediff.</p>
        <?php
        js::monaco_highlighter('<?php\n'
                . 'echo (new reversoLib())->correctionText("Un texte avec une grosse fote");'
                . '\n'
                . '?>');
        debug::print_r("Un texte avec une grosse <del>fote</del><ins>faute</ins>");
    }

    public static function robotstxt() {
        ?>
        <p>
            Cette classe génére le robot.txt <br/>
            elle est appelé par <em>html5.class.php</em> <br/>
            inutile de l'instancier d'avantage.
        </p>
        <?php
    }
}
