// MSEdgeTTS.js
// By LEGAGNEUR Matthieu

MSEdgeTTS = {
    // Voices
    VOICE_AF_ZA_ADRI: 'af-ZA-AdriNeural',
    VOICE_AF_ZA_WILLEM: 'af-ZA-WillemNeural',
    VOICE_SQ_AL_ANILA: 'sq-AL-AnilaNeural',
    VOICE_SQ_AL_ILIR: 'sq-AL-IlirNeural',
    VOICE_AM_ET_AMEHA: 'am-ET-AmehaNeural',
    VOICE_AM_ET_MEKDES: 'am-ET-MekdesNeural',
    VOICE_AR_DZ_AMINA: 'ar-DZ-AminaNeural',
    VOICE_AR_DZ_ISMAEL: 'ar-DZ-IsmaelNeural',
    VOICE_AR_BH_ALI: 'ar-BH-AliNeural',
    VOICE_AR_BH_LAILA: 'ar-BH-LailaNeural',
    VOICE_AR_EG_SALMA: 'ar-EG-SalmaNeural',
    VOICE_AR_EG_SHAKIR: 'ar-EG-ShakirNeural',
    VOICE_AR_IQ_BASSEL: 'ar-IQ-BasselNeural',
    VOICE_AR_IQ_RANA: 'ar-IQ-RanaNeural',
    VOICE_AR_JO_SANA: 'ar-JO-SanaNeural',
    VOICE_AR_JO_TAIM: 'ar-JO-TaimNeural',
    VOICE_AR_KW_FAHED: 'ar-KW-FahedNeural',
    VOICE_AR_KW_NOURA: 'ar-KW-NouraNeural',
    VOICE_AR_LB_LAYLA: 'ar-LB-LaylaNeural',
    VOICE_AR_LB_RAMI: 'ar-LB-RamiNeural',
    VOICE_AR_LY_IMAN: 'ar-LY-ImanNeural',
    VOICE_AR_LY_OMAR: 'ar-LY-OmarNeural',
    VOICE_AR_MA_JAMAL: 'ar-MA-JamalNeural',
    VOICE_AR_MA_MOUNA: 'ar-MA-MounaNeural',
    VOICE_AR_OM_ABDULLAH: 'ar-OM-AbdullahNeural',
    VOICE_AR_OM_AYSHA: 'ar-OM-AyshaNeural',
    VOICE_AR_QA_AMAL: 'ar-QA-AmalNeural',
    VOICE_AR_QA_MOAZ: 'ar-QA-MoazNeural',
    VOICE_AR_SA_HAMED: 'ar-SA-HamedNeural',
    VOICE_AR_SA_ZARIYAH: 'ar-SA-ZariyahNeural',
    VOICE_AR_SY_AMANY: 'ar-SY-AmanyNeural',
    VOICE_AR_SY_LAITH: 'ar-SY-LaithNeural',
    VOICE_AR_TN_HEDI: 'ar-TN-HediNeural',
    VOICE_AR_TN_REEM: 'ar-TN-ReemNeural',
    VOICE_AR_AE_FATIMA: 'ar-AE-FatimaNeural',
    VOICE_AR_AE_HAMDAN: 'ar-AE-HamdanNeural',
    VOICE_AR_YE_MARYAM: 'ar-YE-MaryamNeural',
    VOICE_AR_YE_SALEH: 'ar-YE-SalehNeural',
    VOICE_AZ_AZ_BABEK: 'az-AZ-BabekNeural',
    VOICE_AZ_AZ_BANU: 'az-AZ-BanuNeural',
    VOICE_BN_BD_NABANITA: 'bn-BD-NabanitaNeural',
    VOICE_BN_BD_PRADEEP: 'bn-BD-PradeepNeural',
    VOICE_BN_IN_BASHKAR: 'bn-IN-BashkarNeural',
    VOICE_BN_IN_TANISHAA: 'bn-IN-TanishaaNeural',
    VOICE_BS_BA_GORAN: 'bs-BA-GoranNeural',
    VOICE_BS_BA_VESNA: 'bs-BA-VesnaNeural',
    VOICE_BG_BG_BORISLAV: 'bg-BG-BorislavNeural',
    VOICE_BG_BG_KALINA: 'bg-BG-KalinaNeural',
    VOICE_MY_MM_NILAR: 'my-MM-NilarNeural',
    VOICE_MY_MM_THIHA: 'my-MM-ThihaNeural',
    VOICE_CA_ES_ALBA: 'ca-ES-AlbaNeural',
    VOICE_CA_ES_ENRIC: 'ca-ES-EnricNeural',
    VOICE_CA_ES_JOANA: 'ca-ES-JoanaNeural',
    VOICE_ZH_HK_HIUGAAI: 'zh-HK-HiuGaaiNeural',
    VOICE_ZH_HK_HIUMAAN: 'zh-HK-HiuMaanNeural',
    VOICE_ZH_HK_WANLUNG: 'zh-HK-WanLungNeural',
    VOICE_ZH_CN_XIAOXIAO: 'zh-CN-XiaoxiaoNeural',
    VOICE_ZH_CN_XIAOYI: 'zh-CN-XiaoyiNeural',
    VOICE_ZH_CN_YUNJIAN: 'zh-CN-YunjianNeural',
    VOICE_ZH_CN_YUNXI: 'zh-CN-YunxiNeural',
    VOICE_ZH_CN_YUNXIA: 'zh-CN-YunxiaNeural',
    VOICE_ZH_CN_YUNYANG: 'zh-CN-YunyangNeural',
    VOICE_ZH_CN_LIAONING_XIAOBEI: 'zh-CN-liaoning-XiaobeiNeural',
    VOICE_ZH_TW_HSIAOCHEN: 'zh-TW-HsiaoChenNeural',
    VOICE_ZH_TW_HSIAOYU: 'zh-TW-HsiaoYuNeural',
    VOICE_ZH_TW_YUNJHE: 'zh-TW-YunJheNeural',
    VOICE_ZH_CN_SHAANXI_XIAONI: 'zh-CN-shaanxi-XiaoniNeural',
    VOICE_HR_HR_GABRIJEL: 'hr-HR-GabrijelNeural',
    VOICE_HR_HR_SRECKO: 'hr-HR-SreckoNeural',
    VOICE_CS_CZ_ANTONIN: 'cs-CZ-AntoninNeural',
    VOICE_CS_CZ_VLASTA: 'cs-CZ-VlastaNeural',
    VOICE_DA_DK_CHRISTEL: 'da-DK-ChristelNeural',
    VOICE_DA_DK_JEPPE: 'da-DK-JeppeNeural',
    VOICE_NL_BE_ARNAUD: 'nl-BE-ArnaudNeural',
    VOICE_NL_BE_DENA: 'nl-BE-DenaNeural',
    VOICE_NL_NL_COLETTE: 'nl-NL-ColetteNeural',
    VOICE_NL_NL_FENNA: 'nl-NL-FennaNeural',
    VOICE_NL_NL_MAARTEN: 'nl-NL-MaartenNeural',
    VOICE_EN_AU_ANNETTE: 'en-AU-AnnetteNeural',
    VOICE_EN_AU_CARLY: 'en-AU-CarlyNeural',
    VOICE_EN_AU_DARREN: 'en-AU-DarrenNeural',
    VOICE_EN_AU_DUNCAN: 'en-AU-DuncanNeural',
    VOICE_EN_AU_ELSIE: 'en-AU-ElsieNeural',
    VOICE_EN_AU_FREYA: 'en-AU-FreyaNeural',
    VOICE_EN_AU_JOANNE: 'en-AU-JoanneNeural',
    VOICE_EN_AU_KEN: 'en-AU-KenNeural',
    VOICE_EN_AU_KIM: 'en-AU-KimNeural',
    VOICE_EN_AU_NATASHA: 'en-AU-NatashaNeural',
    VOICE_EN_AU_NEIL: 'en-AU-NeilNeural',
    VOICE_EN_AU_TIM: 'en-AU-TimNeural',
    VOICE_EN_AU_TINA: 'en-AU-TinaNeural',
    VOICE_EN_AU_WILLIAM: 'en-AU-WilliamNeural',
    VOICE_EN_CA_CLARA: 'en-CA-ClaraNeural',
    VOICE_EN_CA_LIAM: 'en-CA-LiamNeural',
    VOICE_EN_HK_SAM: 'en-HK-SamNeural',
    VOICE_EN_HK_YAN: 'en-HK-YanNeural',
    VOICE_EN_IN_AARAV: 'en-IN-AaravNeural',
    VOICE_EN_IN_AASHI: 'en-IN-AashiNeural',
    VOICE_EN_IN_NEERJA: 'en-IN-NeerjaNeural',
    VOICE_EN_IN_PRABHAT: 'en-IN-PrabhatNeural',
    VOICE_EN_IE_CONNOR: 'en-IE-ConnorNeural',
    VOICE_EN_IE_EMILY: 'en-IE-EmilyNeural',
    VOICE_EN_KE_ASILIA: 'en-KE-AsiliaNeural',
    VOICE_EN_KE_CHILEMBA: 'en-KE-ChilembaNeural',
    VOICE_EN_NZ_MITCHELL: 'en-NZ-MitchellNeural',
    VOICE_EN_NZ_MOLLY: 'en-NZ-MollyNeural',
    VOICE_EN_NG_ABEO: 'en-NG-AbeoNeural',
    VOICE_EN_NG_EZINNE: 'en-NG-EzinneNeural',
    VOICE_EN_PH_JAMES: 'en-PH-JamesNeural',
    VOICE_EN_PH_ROSA: 'en-PH-RosaNeural',
    VOICE_EN_SG_LUNA: 'en-SG-LunaNeural',
    VOICE_EN_SG_WAYNE: 'en-SG-WayneNeural',
    VOICE_EN_ZA_LEAH: 'en-ZA-LeahNeural',
    VOICE_EN_ZA_LUKE: 'en-ZA-LukeNeural',
    VOICE_EN_TZ_ELIMU: 'en-TZ-ElimuNeural',
    VOICE_EN_TZ_IMANI: 'en-TZ-ImaniNeural',
    VOICE_EN_GB_ABBI: 'en-GB-AbbiNeural',
    VOICE_EN_GB_ALFIE: 'en-GB-AlfieNeural',
    VOICE_EN_GB_BELLA: 'en-GB-BellaNeural',
    VOICE_EN_GB_ELLIOT: 'en-GB-ElliotNeural',
    VOICE_EN_GB_ETHAN: 'en-GB-EthanNeural',
    VOICE_EN_GB_HOLLIE: 'en-GB-HollieNeural',
    VOICE_EN_GB_LIBBY: 'en-GB-LibbyNeural',
    VOICE_EN_GB_MAISIE: 'en-GB-MaisieNeural',
    VOICE_EN_GB_NOAH: 'en-GB-NoahNeural',
    VOICE_EN_GB_OLIVER: 'en-GB-OliverNeural',
    VOICE_EN_GB_OLIVIA: 'en-GB-OliviaNeural',
    VOICE_EN_GB_RYAN: 'en-GB-RyanNeural',
    VOICE_EN_GB_SONIA: 'en-GB-SoniaNeural',
    VOICE_EN_GB_THOMAS: 'en-GB-ThomasNeural',
    VOICE_EN_US_ANA: 'en-US-AnaNeural',
    VOICE_EN_US_ARIA: 'en-US-AriaNeural',
    VOICE_EN_US_ASHLEY: 'en-US-AshleyNeural',
    VOICE_EN_US_AVA: 'en-US-AvaNeural',
    VOICE_EN_US_ANDREW: 'en-US-AndrewNeural',
    VOICE_EN_US_BRANDON: 'en-US-BrandonNeural',
    VOICE_EN_US_CHRISTOPHER: 'en-US-ChristopherNeural',
    VOICE_EN_US_CORA: 'en-US-CoraNeural',
    VOICE_EN_US_DAVIS: 'en-US-DavisNeural',
    VOICE_EN_US_ELIZABETH: 'en-US-ElizabethNeural',
    VOICE_EN_US_EMMA: 'en-US-EmmaNeural',
    VOICE_EN_US_ERIC: 'en-US-EricNeural',
    VOICE_EN_US_GUY: 'en-US-GuyNeural',
    VOICE_EN_US_JACOB: 'en-US-JacobNeural',
    VOICE_EN_US_JANE: 'en-US-JaneNeural',
    VOICE_EN_US_JASON: 'en-US-JasonNeural',
    VOICE_EN_US_JENNY: 'en-US-JennyNeural',
    VOICE_EN_US_MICHELLE: 'en-US-MichelleNeural',
    VOICE_EN_US_MONICA: 'en-US-MonicaNeural',
    VOICE_EN_US_NANCY: 'en-US-NancyNeural',
    VOICE_EN_US_ROGER: 'en-US-RogerNeural',
    VOICE_EN_US_SARA: 'en-US-SaraNeural',
    VOICE_EN_US_STEFFAN: 'en-US-SteffanNeural',
    VOICE_EN_US_TONY: 'en-US-TonyNeural',
    VOICE_ET_EE_ANU: 'et-EE-AnuNeural',
    VOICE_ET_EE_KERT: 'et-EE-KertNeural',
    VOICE_FIL_PH_ANGELO: 'fil-PH-AngeloNeural',
    VOICE_FIL_PH_BLESSICA: 'fil-PH-BlessicaNeural',
    VOICE_FI_FI_HARRI: 'fi-FI-HarriNeural',
    VOICE_FI_FI_NOORA: 'fi-FI-NooraNeural',
    VOICE_FR_BE_CHARLINE: 'fr-BE-CharlineNeural',
    VOICE_FR_BE_GERARD: 'fr-BE-GerardNeural',
    VOICE_FR_CA_ANTOINE: 'fr-CA-AntoineNeural',
    VOICE_FR_CA_JEAN: 'fr-CA-JeanNeural',
    VOICE_FR_CA_SYLVIE: 'fr-CA-SylvieNeural',
    VOICE_FR_FR_ALAIN: 'fr-FR-AlainNeural',
    VOICE_FR_FR_BRIGITTE: 'fr-FR-BrigitteNeural',
    VOICE_FR_FR_CELESTE: 'fr-FR-CelesteNeural',
    VOICE_FR_FR_CLAUDE: 'fr-FR-ClaudeNeural',
    VOICE_FR_FR_CORALIE: 'fr-FR-CoralieNeural',
    VOICE_FR_FR_DENISE: 'fr-FR-DeniseNeural',
    VOICE_FR_FR_ELOISE: 'fr-FR-EloiseNeural',
    VOICE_FR_FR_HENRI: 'fr-FR-HenriNeural',
    VOICE_FR_FR_JACQUELINE: 'fr-FR-JacquelineNeural',
    VOICE_FR_FR_JEROME: 'fr-FR-JeromeNeural',
    VOICE_FR_FR_JOSEPHINE: 'fr-FR-JosephineNeural',
    VOICE_FR_FR_MAURICE: 'fr-FR-MauriceNeural',
    VOICE_FR_FR_YVES: 'fr-FR-YvesNeural',
    VOICE_FR_FR_YVETTE: 'fr-FR-YvetteNeural',
    VOICE_FR_CH_ARIANE: 'fr-CH-ArianeNeural',
    VOICE_FR_CH_FABRICE: 'fr-CH-FabriceNeural',
    VOICE_GL_ES_ROI: 'gl-ES-RoiNeural',
    VOICE_GL_ES_SABELA: 'gl-ES-SabelaNeural',
    VOICE_KA_GE_EKA: 'ka-GE-EkaNeural',
    VOICE_KA_GE_GIORGI: 'ka-GE-GiorgiNeural',
    VOICE_DE_AT_INGRID: 'de-AT-IngridNeural',
    VOICE_DE_AT_JONAS: 'de-AT-JonasNeural',
    VOICE_DE_DE_AMALA: 'de-DE-AmalaNeural',
    VOICE_DE_DE_BERND: 'de-DE-BerndNeural',
    VOICE_DE_DE_CHRISTOPH: 'de-DE-ChristophNeural',
    VOICE_DE_DE_CONRAD: 'de-DE-ConradNeural',
    VOICE_DE_DE_ELKE: 'de-DE-ElkeNeural',
    VOICE_DE_DE_GISELA: 'de-DE-GiselaNeural',
    VOICE_DE_DE_KASPER: 'de-DE-KasperNeural',
    VOICE_DE_DE_KATJA: 'de-DE-KatjaNeural',
    VOICE_DE_DE_KILLIAN: 'de-DE-KillianNeural',
    VOICE_DE_DE_KLARISSA: 'de-DE-KlarissaNeural',
    VOICE_DE_DE_KLAUS: 'de-DE-KlausNeural',
    VOICE_DE_DE_LOUISA: 'de-DE-LouisaNeural',
    VOICE_DE_DE_MAJA: 'de-DE-MajaNeural',
    VOICE_DE_DE_RALF: 'de-DE-RalfNeural',
    VOICE_DE_DE_TANJA: 'de-DE-TanjaNeural',
    VOICE_DE_CH_JAN: 'de-CH-JanNeural',
    VOICE_DE_CH_LENI: 'de-CH-LeniNeural',
    VOICE_EL_GR_ATHINA: 'el-GR-AthinaNeural',
    VOICE_EL_GR_NESTORAS: 'el-GR-NestorasNeural',
    VOICE_GU_IN_DHWANI: 'gu-IN-DhwaniNeural',
    VOICE_GU_IN_NIRANJAN: 'gu-IN-NiranjanNeural',
    VOICE_HE_IL_AVRI: 'he-IL-AvriNeural',
    VOICE_HE_IL_HILA: 'he-IL-HilaNeural',
    VOICE_HI_IN_MADHUR: 'hi-IN-MadhurNeural',
    VOICE_HI_IN_SWARA: 'hi-IN-SwaraNeural',
    VOICE_HU_HU_NOEMI: 'hu-HU-NoemiNeural',
    VOICE_HU_HU_TAMAS: 'hu-HU-TamasNeural',
    VOICE_IS_IS_GUDRUN: 'is-IS-GudrunNeural',
    VOICE_IS_IS_GUNNAR: 'is-IS-GunnarNeural',
    VOICE_ID_ID_ARDI: 'id-ID-ArdiNeural',
    VOICE_ID_ID_GADIS: 'id-ID-GadisNeural',
    VOICE_GA_IE_COLM: 'ga-IE-ColmNeural',
    VOICE_GA_IE_ORLA: 'ga-IE-OrlaNeural',
    VOICE_IT_IT_BENIGNO: 'it-IT-BenignoNeural',
    VOICE_IT_IT_CALIMERA: 'it-IT-CalimeraNeural',
    VOICE_IT_IT_CATALDO: 'it-IT-CataldoNeural',
    VOICE_IT_IT_DIEGO: 'it-IT-DiegoNeural',
    VOICE_IT_IT_ELSA: 'it-IT-ElsaNeural',
    VOICE_IT_IT_FABIOLA: 'it-IT-FabiolaNeural',
    VOICE_IT_IT_FIAMMA: 'it-IT-FiammaNeural',
    VOICE_IT_IT_GIANNI: 'it-IT-GianniNeural',
    VOICE_IT_IT_IMMACOLATA: 'it-IT-ImmacolataNeural',
    VOICE_IT_IT_IRMA: 'it-IT-IrmaNeural',
    VOICE_IT_IT_ISABELLA: 'it-IT-IsabellaNeural',
    VOICE_IT_IT_LISANDRO: 'it-IT-LisandroNeural',
    VOICE_IT_IT_PALMIRA: 'it-IT-PalmiraNeural',
    VOICE_IT_IT_PIERINA: 'it-IT-PierinaNeural',
    VOICE_IT_IT_RINALDO: 'it-IT-RinaldoNeural',
    VOICE_JA_JP_AOI: 'ja-JP-AoiNeural',
    VOICE_JA_JP_DAICHI: 'ja-JP-DaichiNeural',
    VOICE_JA_JP_HAJIME: 'ja-JP-HajimeNeural',
    VOICE_JA_JP_KEITA: 'ja-JP-KeitaNeural',
    VOICE_JA_JP_MAYU: 'ja-JP-MayuNeural',
    VOICE_JA_JP_MIDORI: 'ja-JP-MidoriNeural',
    VOICE_JA_JP_NANAMI: 'ja-JP-NanamiNeural',
    VOICE_JA_JP_NAOKI: 'ja-JP-NaokiNeural',
    VOICE_JA_JP_SHIORI: 'ja-JP-ShioriNeural',
    VOICE_JV_ID_DIMAS: 'jv-ID-DimasNeural',
    VOICE_JV_ID_SITI: 'jv-ID-SitiNeural',
    VOICE_KN_IN_GAGAN: 'kn-IN-GaganNeural',
    VOICE_KN_IN_SAPNA: 'kn-IN-SapnaNeural',
    VOICE_KK_KZ_AIGUL: 'kk-KZ-AigulNeural',
    VOICE_KK_KZ_DAULET: 'kk-KZ-DauletNeural',
    VOICE_KM_KH_PISETH: 'km-KH-PisethNeural',
    VOICE_KM_KH_SREYMOM: 'km-KH-SreymomNeural',
    VOICE_KO_KR_HYUNSU: 'ko-KR-HyunsuNeural',
    VOICE_KO_KR_INJOON: 'ko-KR-InJoonNeural',
    VOICE_KO_KR_SUNHI: 'ko-KR-SunHiNeural',
    VOICE_LO_LA_CHANTHAVONG: 'lo-LA-ChanthavongNeural',
    VOICE_LO_LA_KEOMANY: 'lo-LA-KeomanyNeural',
    VOICE_LV_LV_EVERITA: 'lv-LV-EveritaNeural',
    VOICE_LV_LV_NILS: 'lv-LV-NilsNeural',
    VOICE_LT_LT_LEONAS: 'lt-LT-LeonasNeural',
    VOICE_LT_LT_ONA: 'lt-LT-OnaNeural',
    VOICE_MK_MK_ALEKSANDAR: 'mk-MK-AleksandarNeural',
    VOICE_MK_MK_MARIJA: 'mk-MK-MarijaNeural',
    VOICE_MS_MY_OSMAN: 'ms-MY-OsmanNeural',
    VOICE_MS_MY_YASMIN: 'ms-MY-YasminNeural',
    VOICE_ML_IN_MIDHUN: 'ml-IN-MidhunNeural',
    VOICE_ML_IN_SOBHANA: 'ml-IN-SobhanaNeural',
    VOICE_MT_MT_GRACE: 'mt-MT-GraceNeural',
    VOICE_MT_MT_JOSEPH: 'mt-MT-JosephNeural',
    VOICE_MR_IN_AAROHI: 'mr-IN-AarohiNeural',
    VOICE_MR_IN_MANOHAR: 'mr-IN-ManoharNeural',
    VOICE_MN_MN_BATAA: 'mn-MN-BataaNeural',
    VOICE_MN_MN_YESUI: 'mn-MN-YesuiNeural',
    VOICE_NE_NP_HEMKALA: 'ne-NP-HemkalaNeural',
    VOICE_NE_NP_SAGAR: 'ne-NP-SagarNeural',
    VOICE_NB_NO_FINN: 'nb-NO-FinnNeural',
    VOICE_NB_NO_ISELIN: 'nb-NO-IselinNeural',
    VOICE_NB_NO_PERNILLE: 'nb-NO-PernilleNeural',
    VOICE_PS_AF_GULNAWAZ: 'ps-AF-GulNawazNeural',
    VOICE_PS_AF_LATIFA: 'ps-AF-LatifaNeural',
    VOICE_FA_IR_DILARA: 'fa-IR-DilaraNeural',
    VOICE_FA_IR_FARID: 'fa-IR-FaridNeural',
    VOICE_PL_PL_MAREK: 'pl-PL-MarekNeural',
    VOICE_PL_PL_ZOFIA: 'pl-PL-ZofiaNeural',
    VOICE_PT_BR_ANTONIO: 'pt-BR-AntonioNeural',
    VOICE_PT_BR_FRANCISCA: 'pt-BR-FranciscaNeural',
    VOICE_PT_PT_DUARTE: 'pt-PT-DuarteNeural',
    VOICE_PT_PT_FERNANDA: 'pt-PT-FernandaNeural',
    VOICE_PT_PT_RAQUEL: 'pt-PT-RaquelNeural',
    VOICE_RO_RO_ALINA: 'ro-RO-AlinaNeural',
    VOICE_RO_RO_EMIL: 'ro-RO-EmilNeural',
    VOICE_RU_RU_DMITRY: 'ru-RU-DmitryNeural',
    VOICE_RU_RU_SVETLANA: 'ru-RU-SvetlanaNeural',
    VOICE_SR_RS_NICHOLAS: 'sr-RS-NicholasNeural',
    VOICE_SR_RS_SOPHIE: 'sr-RS-SophieNeural',
    VOICE_SI_LK_SAMEERA: 'si-LK-SameeraNeural',
    VOICE_SI_LK_THILINI: 'si-LK-ThiliniNeural',
    VOICE_SK_SK_LUKAS: 'sk-SK-LukasNeural',
    VOICE_SK_SK_VIKTORIA: 'sk-SK-ViktoriaNeural',
    VOICE_SL_SI_PETRA: 'sl-SI-PetraNeural',
    VOICE_SL_SI_ROK: 'sl-SI-RokNeural',
    VOICE_SO_SO_MUUSE: 'so-SO-MuuseNeural',
    VOICE_SO_SO_UBAX: 'so-SO-UbaxNeural',
    VOICE_ES_AR_ELENA: 'es-AR-ElenaNeural',
    VOICE_ES_AR_TOMAS: 'es-AR-TomasNeural',
    VOICE_ES_BO_MARCELO: 'es-BO-MarceloNeural',
    VOICE_ES_BO_SOFIA: 'es-BO-SofiaNeural',
    VOICE_ES_CL_CATALINA: 'es-CL-CatalinaNeural',
    VOICE_ES_CL_LORENZO: 'es-CL-LorenzoNeural',
    VOICE_ES_CO_GONZALO: 'es-CO-GonzaloNeural',
    VOICE_ES_CO_SALOME: 'es-CO-SalomeNeural',
    VOICE_ES_CR_JUAN: 'es-CR-JuanNeural',
    VOICE_ES_CR_MARIA: 'es-CR-MariaNeural',
    VOICE_ES_CU_BELKYS: 'es-CU-BelkysNeural',
    VOICE_ES_CU_MANUEL: 'es-CU-ManuelNeural',
    VOICE_ES_DO_EMILIO: 'es-DO-EmilioNeural',
    VOICE_ES_DO_RAMONA: 'es-DO-RamonaNeural',
    VOICE_ES_EC_ANDREA: 'es-EC-AndreaNeural',
    VOICE_ES_EC_LUIS: 'es-EC-LuisNeural',
    VOICE_ES_SV_LORENA: 'es-SV-LorenaNeural',
    VOICE_ES_SV_RODRIGO: 'es-SV-RodrigoNeural',
    VOICE_ES_GQ_JAVIER: 'es-GQ-JavierNeural',
    VOICE_ES_GQ_TERESA: 'es-GQ-TeresaNeural',
    VOICE_ES_GT_ANDRES: 'es-GT-AndresNeural',
    VOICE_ES_GT_MARTA: 'es-GT-MartaNeural',
    VOICE_ES_HN_CARLOS: 'es-HN-CarlosNeural',
    VOICE_ES_HN_KARLA: 'es-HN-KarlaNeural',
    VOICE_ES_MX_BEATRIZ: 'es-MX-BeatrizNeural',
    VOICE_ES_MX_CANDELA: 'es-MX-CandelaNeural',
    VOICE_ES_MX_CARLOTA: 'es-MX-CarlotaNeural',
    VOICE_ES_MX_DALIA: 'es-MX-DaliaNeural',
    VOICE_ES_MX_ELDA: 'es-MX-EldaNeural',
    VOICE_ES_MX_GERARDO: 'es-MX-GerardoNeural',
    VOICE_ES_MX_JORGE: 'es-MX-JorgeNeural',
    VOICE_ES_MX_LARLO: 'es-MX-LarloNeural',
    VOICE_ES_MX_LIBERTO: 'es-MX-LibertoNeural',
    VOICE_ES_MX_LORENZO: 'es-MX-LorenzoNeural',
    VOICE_ES_MX_MARINA: 'es-MX-MarinaNeural',
    VOICE_ES_MX_NILDA: 'es-MX-NildaNeural',
    VOICE_ES_MX_PELAYO: 'es-MX-PelayoNeural',
    VOICE_ES_MX_RENATA: 'es-MX-RenataNeural',
    VOICE_ES_MX_YAGO: 'es-MX-YagoNeural',
    VOICE_ES_NI_FEDERICO: 'es-NI-FedericoNeural',
    VOICE_ES_NI_YOLANDA: 'es-NI-YolandaNeural',
    VOICE_ES_PA_EMILIO: 'es-PA-EmilioNeural',
    VOICE_ES_PA_MARGARITA: 'es-PA-MargaritaNeural',
    VOICE_ES_PY_MARIO: 'es-PY-MarioNeural',
    VOICE_ES_PY_TANIA: 'es-PY-TaniaNeural',
    VOICE_ES_PE_ALEX: 'es-PE-AlexNeural',
    VOICE_ES_PE_CAMILA: 'es-PE-CamilaNeural',
    VOICE_ES_PR_KARINA: 'es-PR-KarinaNeural',
    VOICE_ES_PR_VICTOR: 'es-PR-VictorNeural',
    VOICE_ES_ES_ABRIL: 'es-ES-AbrilNeural',
    VOICE_ES_ES_ALVARO: 'es-ES-AlvaroNeural',
    VOICE_ES_ES_ARNAU: 'es-ES-ArnauNeural',
    VOICE_ES_ES_DARIO: 'es-ES-DarioNeural',
    VOICE_ES_ES_ELVIRA: 'es-ES-ElviraNeural',
    VOICE_ES_ES_ELIAS: 'es-ES-EliasNeural',
    VOICE_ES_ES_ESTHER: 'es-ES-EstherNeural',
    VOICE_ES_ES_IRENE: 'es-ES-IreneNeural',
    VOICE_ES_ES_LIA: 'es-ES-LiaNeural',
    VOICE_ES_ES_NIL: 'es-ES-NilNeural',
    VOICE_ES_ES_SAUL: 'es-ES-SaulNeural',
    VOICE_ES_ES_TEO: 'es-ES-TeoNeural',
    VOICE_ES_ES_TRIANA: 'es-ES-TrianaNeural',
    VOICE_ES_ES_VERA: 'es-ES-VeraNeural',
    VOICE_ES_US_ALONSO: 'es-US-AlonsoNeural',
    VOICE_ES_US_PALOMA: 'es-US-PalomaNeural',
    VOICE_ES_UY_MATEO: 'es-UY-MateoNeural',
    VOICE_ES_UY_VALENTINA: 'es-UY-ValentinaNeural',
    VOICE_ES_VE_PAOLA: 'es-VE-PaolaNeural',
    VOICE_ES_VE_SEBASTIAN: 'es-VE-SebastianNeural',
    VOICE_SU_ID_JAJANG: 'su-ID-JajangNeural',
    VOICE_SU_ID_TUTI: 'su-ID-TutiNeural',
    VOICE_SW_KE_RAFIKI: 'sw-KE-RafikiNeural',
    VOICE_SW_KE_ZURI: 'sw-KE-ZuriNeural',
    VOICE_SW_TZ_DAUDI: 'sw-TZ-DaudiNeural',
    VOICE_SW_TZ_REHEMA: 'sw-TZ-RehemaNeural',
    VOICE_SV_SE_MATTIAS: 'sv-SE-MattiasNeural',
    VOICE_SV_SE_SOFIE: 'sv-SE-SofieNeural',
    VOICE_TA_IN_PALLAVI: 'ta-IN-PallaviNeural',
    VOICE_TA_IN_VALLUVAR: 'ta-IN-ValluvarNeural',
    VOICE_TA_MY_KANI: 'ta-MY-KaniNeural',
    VOICE_TA_MY_SURYA: 'ta-MY-SuryaNeural',
    VOICE_TA_SG_ANBU: 'ta-SG-AnbuNeural',
    VOICE_TA_SG_VENBA: 'ta-SG-VenbaNeural',
    VOICE_TA_LK_KUMAR: 'ta-LK-KumarNeural',
    VOICE_TA_LK_SARANYA: 'ta-LK-SaranyaNeural',
    VOICE_TE_IN_MOHAN: 'te-IN-MohanNeural',
    VOICE_TE_IN_SHRUTI: 'te-IN-ShrutiNeural',
    VOICE_TH_TH_ACHARA: 'th-TH-AcharaNeural',
    VOICE_TH_TH_NIWAT: 'th-TH-NiwatNeural',
    VOICE_TH_TH_PREMWADEE: 'th-TH-PremwadeeNeural',
    VOICE_TR_TR_AHMET: 'tr-TR-AhmetNeural',
    VOICE_TR_TR_EMEL: 'tr-TR-EmelNeural',
    VOICE_UK_UA_OSTAP: 'uk-UA-OstapNeural',
    VOICE_UK_UA_POLINA: 'uk-UA-PolinaNeural',
    VOICE_UR_IN_GUL: 'ur-IN-GulNeural',
    VOICE_UR_IN_SALMAN: 'ur-IN-SalmanNeural',
    VOICE_UR_PK_ASAD: 'ur-PK-AsadNeural',
    VOICE_UR_PK_UZMA: 'ur-PK-UzmaNeural',
    VOICE_UZ_UZ_MADINA: 'uz-UZ-MadinaNeural',
    VOICE_UZ_UZ_SARDOR: 'uz-UZ-SardorNeural',
    VOICE_VI_VN_HOAIMY: 'vi-VN-HoaiMyNeural',
    VOICE_VI_VN_NAMMINH: 'vi-VN-NamMinhNeural',
    VOICE_CY_GB_ALED: 'cy-GB-AledNeural',
    VOICE_CY_GB_NIA: 'cy-GB-NiaNeural',
    VOICE_ZU_ZA_THANDO: 'zu-ZA-ThandoNeural',
    VOICE_ZU_ZA_THEMBA: 'zu-ZA-ThembaNeural',

    // Fixed volume
    VOLUME: '+0%',

    /**
     * Génère un audio TTS à partir des paramètres fournis
     * @param {string} text - Texte a lire.
     * @param {string} [voice=MSEdgeTTS.VOICE_FR_FR_DENISE] - Voix a utiliser.
     * @param {number} [rate=0] - Speech (-50 to +50).
     * @param {number} [pitch=0] - Pitch (-50 to +50).
     */
    TTS: function (text, voice = this.VOICE_FR_FR_DENISE, rate = 0, pitch = 0) {
        rate = Math.max(-50, Math.min(50, rate));
        pitch = Math.max(-50, Math.min(50, pitch));
        let data = JSON.stringify({
            text: text,
            voice: voice,
            rate: (rate >= 0 ? '+' : '-') + Math.abs(rate) + '%',
            pitch: (pitch >= 0 ? '+' : '-') + Math.abs(pitch) + 'Hz',
            volume: this.VOLUME
        });
        let hash = "TTS_" + sha1(data);
        if (localStorage.getItem(hash) != null) {
            $('#MSEdgeTTS_audio').attr('src', 'data:audio/mpeg;base64,' + localStorage.getItem(hash));
            document.getElementById('MSEdgeTTS_audio').play();
        } else {
            $.ajax({
                url: 'https://tts.webextools.com/tts',
                method: 'POST',
                contentType: 'application/json', // Envoie comme JSON
                data: data,
                xhrFields: {
                    responseType: 'arraybuffer'    // Reçoit comme binaire (pour audio)
                },
                success: function (responseData) {
                    let binary = '';
                    const bytes = new Uint8Array(responseData);
                    for (let i = 0; i < bytes.byteLength; i++) {
                        binary += String.fromCharCode(bytes[i]);
                    }
                    let audio = btoa(binary);
                    localStorage.setItem(hash, audio);
                    $('#MSEdgeTTS_audio').attr('src', 'data:audio/mpeg;base64,' + audio);
                    document.getElementById('MSEdgeTTS_audio').play();
                }
            });
    }
    }
};
$(document).ready(function () {
    $("a[data-tts").click(function () {
        let attr = json_decode(strtr($(this).attr("data-tts"), {"'": '"'}));
        MSEdgeTTS.TTS(attr.text, attr.voice, attr.rate, attr.pitch);
    })
});